Repository 2023-Summer-Bootcamp-TeamD/frontend, pull requests merged in 2023-07, with the labels that each got.

#8 [feat/#7] 주석 제거 및 css 작성 방식 변경
  .eslintrc
  public/mockServiceWorker.js
  src/assets/FireExtinguisher.png
  src/assets/KoreanFlag.png
  src/assets/WallClock.png
  src/common/Header/index.tsx
  src/font/KyoboHandwriting2019/KyoboHandwriting2019.woff
  src/font/defalut.css
  src/pages/Main/index.tsx
Labels: REFACTOR

#6 [feat/#3] Header 퍼블리싱 및 assets 추가
  public/mockServiceWorker.js
  src/assets/FireExtinguisher.png
  src/assets/KoreanFlag.png
  src/assets/Teaching.png
  src/assets/WallClock.png
  src/common/NavBar/index.tsx
  src/pages/Main/index.tsx
Labels: DESIGN

#11 [feat/#9] 메인페이지 퍼블리싱
  src/Routes.tsx
  src/assets/BlackBoardDecoInMainPage.png
  src/assets/FireExtinguisher.png
  src/pages/Main/index.tsx
Labels: DESIGN

#22 [feat/#1] 게임페이지 퍼블리싱
  .eslintrc
  package-lock.json
  package.json
  src/App.tsx
  src/Routes.tsx
  src/apis/game.ts
  src/assets/blue.png
  src/assets/chatter.png
  src/assets/eraser.png
  src/assets/pencil.png
  src/assets/school.avif
  src/assets/school2.jpg
  src/assets/sendIcon.png
  src/assets/trashcan.png
  src/components/Game/GameBoard/CanvasDrawingApp/index.tsx
  src/components/Game/GameBoard/GamePointer/index.tsx
  src/components/Game/GameBoard/index.tsx
  src/components/Game/GameContent/index.tsx
  src/components/Game/GameNav/index.tsx
  src/components/Game/StartButton/index.tsx
  src/components/Game/UsersChat/MyMessage/index.tsx
  src/components/Game/UsersChat/OtherMessage/index.tsx
  src/components/Game/UsersChat/chatInputView.tsx
  src/components/Game/UsersChat/index.tsx
  src/components/Game/UsersChat/messageView.tsx
  src/components/Game/UsersChat/title.tsx
  src/constants/chatList.ts
  src/constants/color.ts
  src/constants/users.ts
  src/constants/variants.ts
  src/pages/Game/index.tsx
  src/types/chatRoom.ts
Labels: DESIGN

#14 [feat/#13] 입장페이지 피드백 반영 수정
  .husky/pre-commit
  .husky/pre-push
  src/GlobalStyle.tsx
  src/Routes.tsx
  src/assets/Chatter.png
  src/assets/DoodleCompass.png
  src/assets/DoodleFunctionMath.png
  src/assets/FireExtinguisher.png
  src/assets/Teaching.png
  src/common/Header/index.tsx
  src/components/EnteranceButton/index.tsx
  src/components/EnteranceLabel/index.tsx
  src/pages/EntryRoom/index.tsx
Labels: REFACTOR

#19 [feat/#15] 그림페이지 퍼블리싱
  src/Routes.tsx
  src/assets/Animal.png
  src/assets/Exit.png
  src/assets/Food.png
  src/assets/Person.png
  src/common/DrawingHeader /index.tsx
  src/components/Entrance/ EntranceButton/index.tsx
  src/components/Entrance/EntranceLabel/index.tsx
  src/constants/CircleText.ts
  src/constants/ResultCategory.ts
  src/font/defalut.css
  src/pages/DrawingResult/index.tsx
  src/pages/EntryRoom/index.tsx
Labels: DESIGN

#33 [refactor/#31] ui 구성 assets 위치 통일 및 hover css 적용
  Dockerfile
  docker-compose.yml
  src/components/Entrance/ EntranceButton/index.tsx
  src/components/Game/GameBoard/CanvasDrawingApp/index.tsx
  src/components/Game/GameBoard/index.tsx
  src/components/Game/GameNav/index.tsx
  src/pages/CreatingSpecificRooms/index.tsx
  src/pages/Game/index.tsx
  src/pages/Main/index.tsx
Labels: DESIGN

#53 chore: 프론트엔드 도커설정
  .dockerignore
  Dockerfile
  Dockerfile.prod
Labels: CHORE

#50 [feat/#24] 입장페이지 api 구현
  src/Routes.tsx
  src/apis/entryRoom.ts
  src/main.tsx
  src/pages/EntryRoom/index.tsx
  src/queryClient.ts
  src/types/entryRoom.ts
Labels: FEAT

#57 [refactor/#56] 방 생성 api react-query로 리팩토링
  src/apis/creatingSpecificRooms.ts
  src/pages/CreatingSpecificRooms/index.tsx
  src/types/creatingSpecificRooms.ts
Labels: REFACTOR
